version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django-xa:
    container_name: django-xa
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: xalgo_system_local_django
    depends_on:
      - postgres-xa
      - mailhog-xa
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres-xa:
    container_name: postgres-xa
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: xalgo_system_production_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  mailhog-xa:
    container_name: mailhog
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"

#  docs:
#    image: xalgo_system_local_docs
#    container_name: docs
#    build:
#      context: .
#      dockerfile: ./compose/local/docs/Dockerfile
#    env_file:
#      - ./.envs/.local/.django
#    volumes:
#      - ./docs:/docs:z
#      - ./config:/app/config:z
#      - ./xalgo_system:/app/xalgo_system:z
#    ports:
#      - "7000:7000"
