# Generated by Django 3.0.10 on 2020-10-21 14:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="content",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
