# Generated by Django 3.0.10 on 2020-10-21 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rules", "0002_rule_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="editors",
            field=models.ManyToManyField(
                related_name="editable_rules", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="forked_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rules.Rule",
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="rule_creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_rules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
