# Generated by Django 3.0.10 on 2020-10-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0002_auto_20201024_1721"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="description",
            field=models.CharField(default="Rule description", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rule",
            name="name",
            field=models.CharField(default="Rule Name", max_length=200),
            preserve_default=False,
        ),
    ]
