name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: [ "master" ]
    paths-ignore: [ "docs/**" ]

  push:
    branches: [ "master" ]
    paths-ignore: [ "docs/**" ]


jobs:
  django-lint:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black

      - name: Lint with flake8
        run: flake8 .

      - name: Run black formatter
        run: black . --check


# With no caching at all the entire ci process takes 4m 30s to complete!
  django-test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "postgresql://JlieBPwWambcqHiOtqkcFMVpuWLMeKRZ:pP9iC3wiWbXBYjDDPApDnMJ2h884uSLQeQPcxaS2NLCksV94JineNKnq3Sx3gKnl@postgres/xalgo_system"
      USE_DOCKER: "yes"

    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v2
      - name: Build the Stack
        run:  docker-compose -f development.yml build

      - name: Make DB Migrations
        run:  docker-compose -f development.yml run --rm django python manage.py migrate

      - name: Run the Stack
        run:  docker-compose -f development.yml up -d

      - name: Run Django Tests
        run: |
          docker-compose -f development.yml exec -e DATABASE_URL=${DATABASE_URL} -T django pytest --cov=./
          docker-compose -f development.yml exec -e DATABASE_URL=${DATABASE_URL} -T django coverage xml

      - name: Tear down the Stack
        run:  docker-compose -f development.yml down

      - name: Upload Coverage Report
        run: bash <(curl -s https://codecov.io/bash)
        
  react-build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v2
        
      - uses: actions/setup-node@v2.1.3
        with:
          node-version: '14'

      - name: Install Packages
        run: |
          cd xalgo_system_frontend
          yarn install
          
      - name: Build React App
        run: |
          cd xalgo_system_frontend
          yarn build

  semver:
    runs-on: ubuntu-latest
    needs: [django-lint, django-test, react-build]
    if: github.ref == 'refs/heads/master'

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: "refs/heads/master"
          fetch-depth: 0

      - name: Set up Python 3.8.*
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.*

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python_semantic_release
      - name: Configure Git
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"
      - name: Semantic Release Publish
        run: |
          semantic-release publish -v DEBUG